[package]
name = "day-5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
strum = { version = "0.25.0", features = ["derive"] }
regex = "1.10.2"
itertools = "0.12.0"
rayon = "1.8.0"